import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { createTetragonMonitor, validateAccessEvent } from '../../src/tetragon/monitor';

/**
 * Feature: ebeecontrol, Property 7: Access Event Field Completeness
 *
 * For any access event generated by the Tetragon_Monitor, the event SHALL contain:
 * a positive integer process identifier, a non-empty process binary path, a non-negative
 * integer user identifier, a non-empty pod identifier, a non-empty namespace, a non-empty
 * honeytoken path, an access type from the set {open, read, write, stat}, and a timestamp
 * with millisecond precision.
 *
 * Validates: Requirements 3.2
 */
describe('Feature: ebeecontrol, Property 7: Access Event Field Completeness', () => {
  // Generator for non-empty, non-whitespace-only strings (validateAccessEvent trims before checking)
  const nonEmptyTrimmedString = fc.string({ minLength: 1 }).filter((s) => s.trim().length > 0);

  it('validateAccessEvent returns true for all generated events with valid params', () => {
    const monitor = createTetragonMonitor();

    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 100000 }),
        nonEmptyTrimmedString,
        fc.integer({ min: 0, max: 65535 }),
        nonEmptyTrimmedString,
        nonEmptyTrimmedString,
        nonEmptyTrimmedString,
        fc.constantFrom("open" as const, "read" as const, "write" as const, "stat" as const),
        (processId, processBinaryPath, userId, podId, namespace, honeytokenPath, accessType) => {
          const event = monitor.generateAccessEvent({
            processId,
            processBinaryPath,
            userId,
            podId,
            namespace,
            honeytokenPath,
            accessType,
          });

          expect(validateAccessEvent(event)).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('all individual fields are present and valid for any generated event', () => {
    const monitor = createTetragonMonitor();

    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 100000 }),
        fc.string({ minLength: 1 }),
        fc.integer({ min: 0, max: 65535 }),
        fc.string({ minLength: 1 }),
        fc.string({ minLength: 1 }),
        fc.string({ minLength: 1 }),
        fc.constantFrom("open" as const, "read" as const, "write" as const, "stat" as const),
        (processId, processBinaryPath, userId, podId, namespace, honeytokenPath, accessType) => {
          const event = monitor.generateAccessEvent({
            processId,
            processBinaryPath,
            userId,
            podId,
            namespace,
            honeytokenPath,
            accessType,
          });

          // Positive integer process identifier
          expect(event.processId).toBeGreaterThan(0);
          expect(Number.isInteger(event.processId)).toBe(true);

          // Non-empty process binary path
          expect(typeof event.processBinaryPath).toBe('string');
          expect(event.processBinaryPath.length).toBeGreaterThan(0);

          // Non-negative integer user identifier
          expect(event.userId).toBeGreaterThanOrEqual(0);
          expect(Number.isInteger(event.userId)).toBe(true);

          // Non-empty pod identifier
          expect(typeof event.podId).toBe('string');
          expect(event.podId.length).toBeGreaterThan(0);

          // Non-empty namespace
          expect(typeof event.namespace).toBe('string');
          expect(event.namespace.length).toBeGreaterThan(0);

          // Non-empty honeytoken path
          expect(typeof event.honeytokenPath).toBe('string');
          expect(event.honeytokenPath.length).toBeGreaterThan(0);

          // Access type from the valid set
          expect(['open', 'read', 'write', 'stat']).toContain(event.accessType);

          // Timestamp with millisecond precision (ISO 8601 with .xxx)
          expect(typeof event.timestamp).toBe('string');
          const date = new Date(event.timestamp);
          expect(date.getTime()).not.toBeNaN();
          expect(event.timestamp).toMatch(/\.\d{3}/);
        }
      ),
      { numRuns: 100 }
    );
  });
});
