{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.dynatrace.apiTokenSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dynatrace.apiTokenSecret.name }}
  labels:
    {{- include "ebeecontrol.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.dynatrace.apiTokenSecret.key }}: {{ "" | b64enc | quote }}
{{- end }}
