/**
 * Core TypeScript interfaces and data models for ebeecontrol.
 *
 * These types define the data structures used across all components of the
 * autonomous deception engine: agent orchestrator, Tetragon monitor, Koney deployer,
 * Dynatrace MCP Server client, Vertex AI trainer, and Dynatrace ingestion layer.
 */

// --- Access Event (Tetragon Monitor) ---

/**
 * Represents a kernel-level file access event detected by the Tetragon Monitor.
 * Generated when a process performs an operation on a deployed honeytoken path.
 *
 * Validates: Requirements 3.2
 */
export interface AccessEvent {
  eventId: string;
  processId: number;
  processBinaryPath: string;
  userId: number;
  podId: string;
  namespace: string;
  honeytokenPath: string;
  accessType: "open" | "read" | "write" | "stat";
  timestamp: string; // ISO 8601 with millisecond precision
}

// --- High-Risk Service (Dynatrace MCP Server) ---

/**
 * A Kubernetes service identified by Dynatrace as having elevated vulnerability or exposure.
 * Used during the discovery phase to select honeytoken placement targets.
 *
 * Validates: Requirements 1.2
 */
export interface HighRiskService {
  serviceId: string;
  serviceName: string;
  namespace: string;
  podIdentifiers: string[];
  riskScore: number; // 0-100
}

// --- Pod Context (Dynatrace MCP Server) ---

/**
 * Contextual information about a pod returned by the Dynatrace MCP Server.
 * Used for threat classification during the assessment phase.
 *
 * Validates: Requirements 4.2
 */
export interface PodContext {
  namespace: string;
  namespaceClassification: "production" | "non-production";
  serviceCriticality: number; // 1-5
  davisAnomalyScore: number; // 0.0-1.0
  anomalyWindowMinutes: 10;
}

// --- Threat Assessment ---

/**
 * The result of contextual threat classification for an access event.
 * Determines the response actions to be taken.
 *
 * Validates: Requirements 4.3
 */
export interface ThreatAssessment {
  assessmentId: string;
  accessEventId: string;
  classification: "low" | "medium" | "high" | "critical";
  inputs: {
    namespaceClassification: "production" | "non-production";
    serviceCriticality: number; // 1-5
    davisAnomalyScore: number; // 0.0-1.0
  };
  assessmentTimestamp: string;
  assessmentLatencyMs: number;
}

// --- Honeytoken Registry Entry ---

/**
 * A record of a deployed honeytoken in the agent's registry.
 * Tracks the lifecycle of each honeytoken from deployment through triggering.
 *
 * Validates: Requirements 2.7
 */
export interface HoneytokenRegistryEntry {
  honeytokenId: string; // UUID
  podId: string;
  namespace: string;
  type: "decoy_secret" | "decoy_file" | "decoy_credential";
  filePath: string;
  deploymentTimestamp: string; // ISO 8601
  status: "active" | "triggered" | "decommissioned";
  lastAccessTimestamp?: string;
  accessCount: number;
}

// --- Forensic Report ---

/**
 * A structured forensic report generated by the Gemini model after a threat response.
 * Contains full details of the incident for post-incident analysis.
 *
 * Validates: Requirements 6.2, 6.3
 */
export interface ForensicReport {
  reportId: string; // UUID
  generationTimestamp: string; // ISO 8601
  triggeringAccessEventId: string;
  retentionDays: number; // default 90

  accessEventDetails: {
    processId: number;
    userId: number;
    podId: string;
    namespace: string;
    honeytokenPath: string;
    accessType: "open" | "read" | "write" | "stat";
    timestamp: string;
  };

  contextualAssessment: {
    threatClassification: "low" | "medium" | "high" | "critical";
    podCriticality: number;
    anomalyScore: number;
  };

  responseActions: {
    actionType: string;
    target: string;
    timestamp: string;
    result: "success" | "failure";
  }[];

  timeline: {
    eventDescription: string;
    timestamp: string;
  }[];

  recommendedFollowUpActions: string[]; // at least 1
}

// --- Audit Log Entry ---

/**
 * A record of an autonomous decision made by the Ebeecontrol Agent.
 * All decisions are logged for accountability and compliance.
 *
 * Validates: Requirements 5.4, 8.6
 */
export interface AuditLogEntry {
  entryId: string;
  timestamp: string; // ISO 8601
  decisionType: "discovery" | "deployment" | "assessment" | "response" | "learning" | "model_update";
  decisionRationale: string;
  inputDataSummary: string;
  outcome: string;
  retentionDays: number; // minimum 90
}

// --- Response Action ---

/**
 * A threat response action executed by the Ebeecontrol Agent.
 * Tracks the action type, target, and result for audit and reporting.
 *
 * Validates: Requirements 5.4
 */
export interface ResponseAction {
  actionId: string;
  actionType: "pod_isolation" | "ip_block" | "additional_honeytokens" | "alert";
  target: string;
  timestamp: string;
  threatClassification: "low" | "medium" | "high" | "critical";
  result: "success" | "failure";
  retryCount: number;
}

// --- Placement Model (Vertex AI) ---

/**
 * Represents a trained placement optimization model from Vertex AI.
 * Published only when validation accuracy meets or exceeds the current model.
 *
 * Validates: Requirements 7.4
 */
export interface PlacementModel {
  versionId: string;
  trainingDatasetSize: number;
  validationAccuracy: number; // percentage
  publishedTimestamp: string;
  modelArtifactUri: string;
}

// --- Outcome Data (Vertex AI) ---

/**
 * Data submitted to the Vertex AI Trainer after a threat response sequence.
 * Used to train and improve the placement optimization model.
 *
 * Validates: Requirements 7.1
 */
export interface OutcomeData {
  incidentId: string;
  accessEvent: AccessEvent;
  honeytokenType: "decoy_secret" | "decoy_file" | "decoy_credential";
  placementLocation: string;
  actionsTaken: ResponseAction[];
  effectiveness: {
    detectionToResponseLatencySeconds: number;
    threatContained: boolean;
    falsePositive: boolean;
  };
  timestamp: string;
}

// --- Configuration ---

/**
 * Full configuration for the ebeecontrol system.
 * All intervals and timeouts are configurable with sensible defaults.
 *
 * Validates: Requirements 8.2, 8.3, 7.3
 */
export interface EbeecontrolConfig {
  discovery: {
    intervalMinutes: number; // 5-1440, default 60
  };
  healthCheck: {
    intervalSeconds: number; // default 30
    responseTimeoutSeconds: number; // default 5
    componentTimeoutSeconds: number; // default 10
  };
  deployment: {
    maxHoneytokensPerPod: number; // 1-5
    deploymentTimeoutSeconds: number; // default 30
  };
  response: {
    isolationTimeoutSeconds: number; // default 10
    isolationMaxRetries: number; // default 3
    isolationRetryIntervalSeconds: number; // default 5
    ipBlockMaxRetries: number; // default 3
    ipBlockRetryIntervalSeconds: number; // default 5
  };
  reporting: {
    reportRetentionDays: number; // default 90
    reportGenerationTimeoutSeconds: number; // default 60
    reportGenerationMaxRetries: number; // default 3
  };
  learning: {
    retrainingIntervalHours: number; // 1-168, default 24
    minimumOutcomeRecords: number; // default 50
    outcomeSubmissionTimeoutSeconds: number; // default 60
  };
  auditLog: {
    retentionDays: number; // minimum 90
  };
  notifications: {
    channelEndpoint: string;
  };
  dynatraceIngestion: {
    metricsEndpoint: string; // Dynatrace Metrics API v2 endpoint URL
    logEndpoint: string; // Dynatrace Log Ingestion API endpoint URL
    apiToken: string; // Dynatrace API token (metrics.ingest, logs.ingest scopes)
    requestTimeoutSeconds: number; // default 10
    retryConfig: {
      maxRetries: number; // default 5
      initialBackoffSeconds: number; // default 2
      backoffMultiplier: number; // default 2 (exponential)
      maxBackoffSeconds: number; // default 32
    };
    batchConfig: {
      maxBatchSize: number; // default 100 items per batch
      flushIntervalSeconds: number; // default 5
    };
  };
}
