/**
 * eBeeControl Live Demo — Pushes real data to Dynatrace
 *
 * This script runs the full attack simulation and pushes all events
 * to your Dynatrace environment so you can see them on the dashboard.
 *
 * Prerequisites:
 *   export DYNATRACE_ENV_URL=https://abc12345.live.dynatrace.com
 *   export DYNATRACE_API_TOKEN=dt0c01.XXXXX
 *
 * Run: npx tsx scripts/demo-live.ts
 */

import { DynatraceMetricsIngestionClient } from '../src/dynatrace-ingestion/metrics-client.js';
import { DynatraceLogIngestionClient } from '../src/dynatrace-ingestion/log-client.js';
import { createEventBroadcaster } from '../src/dynatrace-ingestion/event-broadcaster.js';
import { createHoneytokenRegistry } from '../src/agent/registry.js';
import { createAuditLog } from '../src/agent/audit-log.js';
import { createReportGenerator } from '../src/agent/report-generator.js';
import { createLearningFeedbackLoop } from '../src/agent/learning-feedback.js';
import { VertexAiTrainer } from '../src/vertex/trainer.js';
import { classifyThreat } from '../src/agent/threat-classifier.js';
import { generateResponsePlan } from '../src/agent/response-planner.js';
import { executeResponse } from '../src/agent/response-executor.js';
import { createHttpClient } from '../src/utils/http-client.js';
import { AccessEvent, PodContext, HoneytokenRegistryEntry, ThreatAssessment, ResponseAction } from '../src/types/index.js';
import { DynatraceIngestionConfig } from '../src/config.js';
import { v4 as uuidv4 } from 'uuid';

// ─── Configuration ────────────────────────────────────────────────────────────

const DYNATRACE_ENV_URL = process.env.DYNATRACE_ENV_URL;
const DYNATRACE_API_TOKEN = process.env.DYNATRACE_API_TOKEN;

if (!DYNATRACE_ENV_URL || !DYNATRACE_API_TOKEN) {
  console.error('❌ Missing environment variables:');
  console.error('   export DYNATRACE_ENV_URL=https://abc12345.live.dynatrace.com');
  console.error('   export DYNATRACE_API_TOKEN=dt0c01.XXXXX');
  process.exit(1);
}

const ingestionConfig: DynatraceIngestionConfig = {
  metricsEndpoint: `${DYNATRACE_ENV_URL}/api/v2/metrics/ingest`,
  logEndpoint: `${DYNATRACE_ENV_URL}/api/v2/logs/ingest`,
  apiToken: DYNATRACE_API_TOKEN,
  requestTimeoutSeconds: 10,
  retryConfig: {
    maxRetries: 3,
    initialBackoffSeconds: 2,
    backoffMultiplier: 2,
    maxBackoffSeconds: 16,
  },
  batchConfig: {
    maxBatchSize: 50,
    flushIntervalSeconds: 2,
  },
};

// ─── Setup ────────────────────────────────────────────────────────────────────

const httpClient = createHttpClient();
const metricsClient = new DynatraceMetricsIngestionClient(ingestionConfig, httpClient);
const logClient = new DynatraceLogIngestionClient(ingestionConfig, httpClient);
const broadcaster = createEventBroadcaster(metricsClient, logClient);
const registry = createHoneytokenRegistry();
const auditLog = createAuditLog();
const vertexTrainer = new VertexAiTrainer();
const learningLoop = createLearningFeedbackLoop(vertexTrainer, auditLog);
const reportGenerator = createReportGenerator(
  async () => 'Forensic report generated by Gemini'
);

// ─── Demo ─────────────────────────────────────────────────────────────────────

async function runLiveDemo() {
  console.log('');
  console.log('╔══════════════════════════════════════════════════════════════╗');
  console.log('║      🐝 eBeeControl — Live Dynatrace Demo                  ║');
  console.log('╚══════════════════════════════════════════════════════════════╝');
  console.log('');
  console.log(`   Dynatrace: ${DYNATRACE_ENV_URL}`);
  console.log('');

  // ── Step 1: Deploy honeytokens and push to Dynatrace ──
  console.log('📡 Step 1: Deploying honeytokens...');

  const honeytokens: HoneytokenRegistryEntry[] = [
    {
      honeytokenId: uuidv4(),
      podId: 'pod-payment-7f8d9c',
      namespace: 'production',
      type: 'decoy_secret',
      filePath: '/var/run/secrets/kubernetes.io/serviceaccount/decoy-token',
      deploymentTimestamp: new Date().toISOString(),
      status: 'active',
      accessCount: 0,
    },
    {
      honeytokenId: uuidv4(),
      podId: 'pod-auth-x9y8z7',
      namespace: 'production',
      type: 'decoy_file',
      filePath: '/tmp/.config/credentials.json',
      deploymentTimestamp: new Date().toISOString(),
      status: 'active',
      accessCount: 0,
    },
    {
      honeytokenId: uuidv4(),
      podId: 'pod-userdata-k5m6n7',
      namespace: 'production',
      type: 'decoy_credential',
      filePath: '/home/app/.ssh/id_rsa_prod',
      deploymentTimestamp: new Date().toISOString(),
      status: 'active',
      accessCount: 0,
    },
  ];

  for (const ht of honeytokens) {
    registry.addEntry(ht);
    await broadcaster.broadcastHoneytokenRegistryChange(ht);
    console.log(`   🍯 Deployed: ${ht.type} → ${ht.podId}`);
  }

  // Push health status
  await broadcaster.broadcastHealthStatusChange({
    componentName: 'Tetragon_Monitor',
    status: 'healthy',
    lastSuccessfulCheckTimestamp: new Date().toISOString(),
  });
  await broadcaster.broadcastHealthStatusChange({
    componentName: 'Koney_Deployer',
    status: 'healthy',
    lastSuccessfulCheckTimestamp: new Date().toISOString(),
  });
  await broadcaster.broadcastHealthStatusChange({
    componentName: 'Dynatrace_MCP_Server',
    status: 'healthy',
    lastSuccessfulCheckTimestamp: new Date().toISOString(),
  });
  await broadcaster.broadcastHealthStatusChange({
    componentName: 'Vertex_AI_Trainer',
    status: 'healthy',
    lastSuccessfulCheckTimestamp: new Date().toISOString(),
  });

  await metricsClient.flush();
  console.log('   ✅ Metrics pushed to Dynatrace');
  console.log('');

  await sleep(2000);

  // ── Step 2: Simulate attack ──
  console.log('⚔️  Step 2: Simulating attack...');

  const attackEvent: AccessEvent = {
    eventId: uuidv4(),
    processId: 31337,
    processBinaryPath: '/tmp/.hidden/reverse-shell',
    userId: 0,
    podId: 'pod-payment-7f8d9c',
    namespace: 'production',
    honeytokenPath: '/var/run/secrets/kubernetes.io/serviceaccount/decoy-token',
    accessType: 'read',
    timestamp: new Date().toISOString(),
  };

  console.log(`   ⚠️  Attack: PID ${attackEvent.processId} reading ${attackEvent.honeytokenPath}`);

  // ── Step 3: Assess threat ──
  console.log('');
  console.log('🧠 Step 3: Assessing threat...');

  const podContext: PodContext = {
    namespace: 'production',
    namespaceClassification: 'production',
    serviceCriticality: 4,
    davisAnomalyScore: 0.85,
    anomalyWindowMinutes: 10,
  };

  const classification = classifyThreat(podContext);
  const assessment: ThreatAssessment = {
    assessmentId: uuidv4(),
    accessEventId: attackEvent.eventId,
    classification,
    inputs: {
      namespaceClassification: podContext.namespaceClassification,
      serviceCriticality: podContext.serviceCriticality,
      davisAnomalyScore: podContext.davisAnomalyScore,
    },
    assessmentTimestamp: new Date().toISOString(),
    assessmentLatencyMs: 2,
  };

  console.log(`   🎯 Classification: ${classification.toUpperCase()}`);

  // Broadcast access event
  await broadcaster.broadcastAccessEvent(attackEvent, classification);

  await sleep(1000);

  // ── Step 4: Execute response ──
  console.log('');
  console.log('⚡ Step 4: Executing response...');

  const plan = generateResponsePlan(assessment, {
    namespace: attackEvent.namespace,
    podId: attackEvent.podId,
  });

  const responseResult = await executeResponse(plan, assessment, {
    isolatePod: async (podId) => {
      console.log(`   🔒 Pod ${podId} isolated`);
    },
    blockIp: async (podId) => {
      console.log(`   🚫 IP blocked for ${podId}`);
    },
    deployHoneytokens: async (ns, count) => {
      console.log(`   🍯 ${count} additional honeytokens deployed in ${ns}`);
    },
    sendAlert: async () => {},
    auditLog,
  });

  // Broadcast response actions
  for (const action of responseResult.actions) {
    await broadcaster.broadcastResponseAction(action);
  }

  // Update registry
  registry.updateStatus(honeytokens[0].honeytokenId, 'triggered');
  await broadcaster.broadcastHoneytokenRegistryChange({
    ...honeytokens[0],
    status: 'triggered',
  });

  await sleep(1000);

  // ── Step 5: Generate report ──
  console.log('');
  console.log('📋 Step 5: Generating forensic report...');

  const report = await reportGenerator.generate({
    accessEvent: attackEvent,
    threatAssessment: assessment,
    responseActions: responseResult.actions,
  });

  await broadcaster.broadcastForensicReport(report);
  console.log(`   📄 Report: ${report.reportId}`);

  // ── Step 6: Submit learning outcome ──
  console.log('');
  console.log('🧬 Step 6: Submitting to Vertex AI...');

  await learningLoop.submitOutcome(
    {
      incidentId: uuidv4(),
      accessEvent: attackEvent,
      honeytokenType: 'decoy_secret',
      placementLocation: attackEvent.honeytokenPath,
    },
    {
      actionsTaken: responseResult.actions,
      effectiveness: {
        detectionToResponseLatencySeconds: 0.002,
        threatContained: true,
        falsePositive: false,
      },
    }
  );

  await broadcaster.broadcastLearningMetrics({
    modelVersionId: vertexTrainer.getCurrentModelVersion().versionId,
    validationAccuracy: vertexTrainer.getCurrentModelVersion().validationAccuracy,
    trainingDatasetSize: vertexTrainer.getDatasetSize(),
    trainingStatus: 'idle',
  });

  // ── Step 7: Broadcast incident timeline ──
  await broadcaster.broadcastIncidentTimeline({
    incidentId: uuidv4(),
    timestamp: attackEvent.timestamp,
    threatClassification: classification,
    affectedPodId: attackEvent.podId,
    namespace: attackEvent.namespace,
    responseActions: responseResult.actions.map(a => ({
      actionType: a.actionType,
      outcome: a.result,
    })),
    finalOutcome: 'contained',
  });

  console.log('   ✅ Outcome submitted');

  // ── Flush all data to Dynatrace ──
  console.log('');
  console.log('📤 Flushing all data to Dynatrace...');
  await metricsClient.flush();
  await logClient.flush();

  console.log('   ✅ All data pushed to Dynatrace');
  console.log('');
  console.log('╔══════════════════════════════════════════════════════════════╗');
  console.log('║   ✅ Demo complete! Check your Dynatrace Dashboard          ║');
  console.log(`║   ${DYNATRACE_ENV_URL}                                      `);
  console.log('╚══════════════════════════════════════════════════════════════╝');
  console.log('');
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

runLiveDemo().catch((error) => {
  console.error('Demo failed:', error);
  process.exit(1);
});
